-- Leader Automobile / Supabase
-- Exécute ce script dans Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  created_at timestamptz not null default now()
);

create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  reference text unique not null,
  name text not null,
  category text not null check (category in ('occasion','neuve','arrivage')),
  year integer,
  mileage integer,
  price numeric,
  currency text not null default 'FCFA',
  fuel text,
  transmission text,
  description text,
  status text not null default 'disponible' check (status in ('disponible','vendu','masque')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vehicle_images (
  id bigint generated by default as identity primary key,
  vehicle_id bigint not null references public.vehicles(id) on delete cascade,
  storage_path text not null,
  public_url text not null,
  position integer not null default 0,
  is_main boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null,
  vehicle_wanted text,
  vehicle_id bigint references public.vehicles(id) on delete set null,
  wanted_date date,
  wanted_time time,
  appointment_type text,
  message text,
  status text not null default 'nouveau' check (status in ('nouveau','contacte','confirme','termine','annule')),
  created_at timestamptz not null default now()
);

create index if not exists vehicles_status_idx on public.vehicles(status);
create index if not exists vehicles_category_idx on public.vehicles(category);
create index if not exists vehicle_images_vehicle_id_idx on public.vehicle_images(vehicle_id);
create index if not exists appointments_status_idx on public.appointments(status);

-- Fonction utilisée par les policies. Elle évite une récursion sur admin_users.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.admin_users
    where id = auth.uid()
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;

alter table public.admin_users enable row level security;
alter table public.vehicles enable row level security;
alter table public.vehicle_images enable row level security;
alter table public.appointments enable row level security;

drop policy if exists "admin can read own admin record" on public.admin_users;
create policy "admin can read own admin record"
on public.admin_users for select
to authenticated
using (id = auth.uid());

drop policy if exists "public can read visible vehicles" on public.vehicles;
create policy "public can read visible vehicles"
on public.vehicles for select
to anon, authenticated
using (status <> 'masque');

drop policy if exists "admins can manage vehicles" on public.vehicles;
create policy "admins can manage vehicles"
on public.vehicles for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "public can read visible vehicle images" on public.vehicle_images;
create policy "public can read visible vehicle images"
on public.vehicle_images for select
to anon, authenticated
using (
  exists (
    select 1 from public.vehicles v
    where v.id = vehicle_images.vehicle_id
      and v.status <> 'masque'
  )
);

drop policy if exists "admins can manage vehicle images" on public.vehicle_images;
create policy "admins can manage vehicle images"
on public.vehicle_images for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "public can create appointments" on public.appointments;
create policy "public can create appointments"
on public.appointments for insert
to anon, authenticated
with check (status = 'nouveau');

drop policy if exists "admins can read appointments" on public.appointments;
create policy "admins can read appointments"
on public.appointments for select
to authenticated
using (public.is_admin());

drop policy if exists "admins can update appointments" on public.appointments;
create policy "admins can update appointments"
on public.appointments for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins can delete appointments" on public.appointments;
create policy "admins can delete appointments"
on public.appointments for delete
to authenticated
using (public.is_admin());

-- Bucket public pour les photos des véhicules.
insert into storage.buckets (id, name, public)
values ('vehicle-images', 'vehicle-images', true)
on conflict (id) do update set public = true;

drop policy if exists "public can view vehicle images" on storage.objects;
create policy "public can view vehicle images"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'vehicle-images');

drop policy if exists "admins can upload vehicle images" on storage.objects;
create policy "admins can upload vehicle images"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'vehicle-images'
  and public.is_admin()
);

drop policy if exists "admins can update vehicle images" on storage.objects;
create policy "admins can update vehicle images"
on storage.objects for update
to authenticated
using (bucket_id = 'vehicle-images' and public.is_admin())
with check (bucket_id = 'vehicle-images' and public.is_admin());

drop policy if exists "admins can delete vehicle images" on storage.objects;
create policy "admins can delete vehicle images"
on storage.objects for delete
to authenticated
using (bucket_id = 'vehicle-images' and public.is_admin());

-- Après avoir créé l'utilisateur admin dans Supabase Auth,
-- remplace l'email ci-dessous par son adresse puis exécute :
-- insert into public.admin_users (id, email)
-- select id, email from auth.users
-- where email = 'admin@leaderautomobile.com';

-- Le mot de passe utilisé par le formulaire de code est : 2027
-- Configure le compte admin@leaderautomobile.com avec ce mot de passe dans Supabase Auth.
